### ISSUE TITLE
Sound and Light screens should probably not have "side view"

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/waves-intro#10]
Side view does not work for the Sound and Light Screens. These radio button options should probably just be removed from these two screens.

**Comment by ariel-phet** [comment]
Tagging @arouinfar if she has any objections.

**Comment by arouinfar** [comment]
No strong objections from me. I will say that it was pretty neutral in interviews, and it likely won't cause any issues, but I also don't think it's that pedagogically important for this sim, either.

We should probably also check in with @kathy-phet before removing these controls.

**Comment by samreid** [comment]
To clarify, the proposal is to remove the "Top View" / "Side View" radio buttons from Waves Intro sim, screen 2 and screen 3, but to leave the radio buttons in the Wave Interference sim on screen 1 scene 2 and scene 3?

**Comment by arouinfar** [comment]
> To clarify, the proposal is to remove the "Top View" / "Side View" radio buttons from Waves Intro sim, screen 2 and screen 3, but to leave the radio buttons in the Wave Interference sim on screen 1 scene 2 and scene 3?

Yes, that's what I was thinking.

**Comment by ariel-phet** [comment]
Sorry, I think I confused myself, I think it just "felt" like the side view wasn't working. We can disregard this issue. I think I might make a separate one, as for the other scenes it is just not as obvious that your are in "side" mode...I know that is sort of the point since it is a spherical wave, but I might suggest a future polish.
