### ISSUE TITLE
Waves Intro Sound Feature Video Script & Recording

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/waves-intro#12]
Make sound features video script and review with team

https://drive.google.com/open?id=1oEsxTJ5rjlwOd_quH1o9R47VsJw7j2IboGhk9fNaDhU

Recording will happen after.

**Comment by brettfiedler** [comment]
Script complete, ready for review

https://docs.google.com/document/d/1oEsxTJ5rjlwOd_quH1o9R47VsJw7j2IboGhk9fNaDhU/edit?usp=sharing

**Comment by emily-phet** [comment]
@BLFiedler - I made a few edits, and noticed a couple of things that would be good to have tightly coupled with the disciplinary goals of the sim (particularly in the area related to the Sound screen). I've asked the full team to take a look, emphasizing that we are looking for specific feedback, a few wording tweaks, and plan to be done before March 31st.

**Comment by emily-phet** [comment]
@BLFiedler Please message me about this in a few days regarding next steps.

**Comment by emily-phet** [comment]
@BLFiedler - please bring this to MAL sound meeting tomorrow. We can confirm there that there will be no enhanced sounds, and also consider other descriptors for the sounds. I'm not sure about Ping or wubwub, etc. but others might prefer them, or have a few quick brainstormed ideas for different ones.

**Comment by brettfiedler** [comment]
Waiting on waves:intro to go through RC and there is guaranteed to be no revisions to the sounds before producing a final draft and publishing to YT/PhET site.

**Comment by brettfiedler** [comment]
Published after hearign about sim publication today. See sim page.

https://phet.colorado.edu/en/simulation/waves-intro
