### ISSUE TITLE
Screen icons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/waves-intro#2]
Since waves-intro has its own repo now, I'm moving https://github.com/phetsims/wave-interference/issues/358 to this issue.

@samreid wrote:
>As part of https://github.com/phetsims/wave-interference/issues/356 we will need icons for the screens.  Currently it looks like this:
>
>![image](https://user-images.githubusercontent.com/679486/54932685-d6821180-4ee0-11e9-8df8-f81e476e43e1.png)

I replied:
> A few ideas to mock up:
>
>- Scene icons from Wave Interference
>- Each source emitting a wave
>- More iconic view of the screens, e.g. water drop, music note

**Comment by arouinfar** [comment]
I've mocked up a few options for review in a design meeting.

Each source emitting a wave
<img src="https://user-images.githubusercontent.com/8419308/55759476-aaa17880-5a16-11e9-93f2-3a58993392e7.png" width=180> <img src="https://user-images.githubusercontent.com/8419308/55759477-ab3a0f00-5a16-11e9-8fac-abe2cb23fe75.png" width=180> <img src="https://user-images.githubusercontent.com/8419308/55759469-aaa17880-5a16-11e9-802c-2a6fb4b9191d.png" width=180>

Iconic version of each source
<img src="https://user-images.githubusercontent.com/8419308/55759475-aaa17880-5a16-11e9-969d-5c5ff5ccd504.png" width=180> <img src="https://user-images.githubusercontent.com/8419308/55759470-aaa17880-5a16-11e9-9040-82ff9cb6b4b9.png" width=180> <img src="https://user-images.githubusercontent.com/8419308/55759471-aaa17880-5a16-11e9-8564-40a053e3424a.png" width=180>

Iconic representation of water, sound, light
<img src="https://user-images.githubusercontent.com/8419308/55759472-aaa17880-5a16-11e9-8ff8-b03ece885929.png" width=180> <img src="https://user-images.githubusercontent.com/8419308/55759473-aaa17880-5a16-11e9-86b3-650af9bb8dd3.png" width=180> <img src="https://user-images.githubusercontent.com/8419308/55759474-aaa17880-5a16-11e9-9280-25fc25d46b3f.png" width =180>

**Comment by samreid** [comment]
I'm not sure how to improve it further, but "Iconic version of each source" seems like a great direction.

**Comment by samreid** [comment]
At today's meeting, @kathy-phet and @ariel-phet also expressed a preference for "Iconic version of each source".

**Comment by samreid** [comment]
@kathy-phet and @ariel-phet additionally suggested some iconic waves coming out of the sound source (like curved wavefronts) and a glow/light rays coming out of the light source.  So they have an equivalent to the drop of water.

**Comment by arouinfar** [comment]
Thanks @samreid! I'll work on some iterations of the "Iconic version of each source" icons.

**Comment by arouinfar** [comment]
@samreid @ariel-phet here's an updated draft of the icons showing iconic waves/glow. Is the direction you were imagining? 
<img src="https://user-images.githubusercontent.com/8419308/56238270-50726a00-604b-11e9-92aa-03a4043beae3.png" width=200> <img src="https://user-images.githubusercontent.com/8419308/56238268-50726a00-604b-11e9-9e0d-7a2052593082.png" width=200> <img src="https://user-images.githubusercontent.com/8419308/56238269-50726a00-604b-11e9-9ee5-e769a6e90856.png" width=200>

**Comment by ariel-phet** [comment]
@arouinfar those are spot on to what I was imagining! Looks great to me!

**Comment by ariel-phet** [comment]
@arouinfar can you make a finalized draft of these for @samreid to use in the sim?

**Comment by arouinfar** [comment]
Thanks @ariel-phet! Here are the assets @samreid.
[screen_icons.zip](https://github.com/phetsims/waves-intro/files/3092381/screen_icons.zip)

**Comment by kathy-phet** [comment]
@arouinfar - Can I suggest a slight change? It would be to make the laser light not rounded but cone spreading out. Simply because light doesn't curve and this sort of suggests that it does.

**Comment by arouinfar** [comment]
> @arouinfar - Can I suggest a slight change? It would be to make the laser light not rounded but cone spreading out. Simply because light doesn't curve and this sort of suggests that it does.

Thanks @kathy-phet. I used a circle to create the gradient, but adjusted the clipping mask so it appears conical instead.

![light_screen_icon](https://user-images.githubusercontent.com/8419308/56380292-0b774080-61cf-11e9-9986-c1afcb743d4c.png)

@samreid here are the finalized screen icons. [screen_icons_2.zip](https://github.com/phetsims/waves-intro/files/3095554/screen_icons_2.zip)

**Comment by samreid** [comment]
I added the screen icons, they look great in context.  Thanks @arouinfar!  Ready for your review.

**Comment by arouinfar** [comment]
Looks great, thanks @samreid!
