### ISSUE TITLE
Unused option: "supportsSound"?

### ISSUE THREAD

**Issue by zepumph** [phetsims/waves-intro#25]
Over in https://github.com/phetsims/chipper/issues/1031 I found an option passed to Screens in waves-intro that I don't think is used. @samreid can you speak to this, and delete if they are unused or explain?

https://github.com/phetsims/waves-intro/blob/0c0f3864c41ca209aa59d55ab3029b52e842d98b/js/waves-intro-main.js#L60

**Comment by zepumph** [comment]
maybe it is related to the `audioEnabled` options I see in waves intro Screens and ScreenViews.

**Comment by samreid** [comment]
Thanks, it seems this was replaced with `audioEnabled` in the parent types, which defaults to true, so I removed this stale one. Closing.
