### ISSUE TITLE
Seam in top and right edge of the pipe

### ISSUE THREAD

**Issue by samreid** [phetsims/waves-intro#5]
The artwork for the homescreen icons looks great, but I noticed a "seam" at the top and right of the pipe.  I realize this probably came from the original code that made this, but thought it would be good to clean up before publication:

![image](https://user-images.githubusercontent.com/679486/56592390-d17bb500-65a7-11e9-9b94-8e2324a47c95.png)

@arouinfar can you please take a look?

**Comment by arouinfar** [comment]
Good catch @samreid. I think the pipe artwork didn't scale properly when I made the icons. I've adjusted the corner piece, and it now looks like this:
![water_screen_icon](https://user-images.githubusercontent.com/8419308/56598826-81562000-65b2-11e9-8564-51068feb4901.png)

Here are the updated assets.
[water_screen_icon.zip](https://github.com/phetsims/waves-intro/files/3108622/water_screen_icon.zip)

**Comment by samreid** [comment]
Thanks, it looks great and I added it to the sim.  Closing.
