### ISSUE TITLE
Screenshot for 1.0

### ISSUE THREAD

**Issue by samreid** [phetsims/waves-intro#8]
Waves Intro is a new simulation which has been though dev testing and is ready for its first RC.  We will need a screenshot for publication. The steps to create the screenshot are described here: https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots

@KatieWoe @arouinfar @ariel-phet who is responsible for creating the screenshot? What should the screenshot depict?

**Comment by KatieWoe** [comment]
Generally @arouinfar decides what it will depict, posts it here, and then I create the official screenshots with the correct aspect ratio etc.

**Comment by arouinfar** [comment]
@KatieWoe I'll take some screenshots this afternoon

**Comment by arouinfar** [comment]
Main:
![Waves Intro screenshot](https://user-images.githubusercontent.com/8419308/62969763-34998d80-bdcb-11e9-95ce-b0197fe623fc.png)

Alt 1:
![Waves Intro screenshot (1)](https://user-images.githubusercontent.com/8419308/62969761-34998d80-bdcb-11e9-9114-ee9ed66caefb.png)

Alt 2:
![Waves Intro screenshot (2)](https://user-images.githubusercontent.com/8419308/62969762-34998d80-bdcb-11e9-97cc-3337479fb02c.png)

**Comment by KatieWoe** [comment]
Screenshots:
![waves-intro-screenshot](https://user-images.githubusercontent.com/41024075/63189363-0ca36780-c021-11e9-8dfe-11ab8e6ece41.png)
![waves-intro-screenshot-alt1](https://user-images.githubusercontent.com/41024075/63189364-0d3bfe00-c021-11e9-8ea8-b8c2c858a8c2.png)
![waves-intro-screenshot-alt2](https://user-images.githubusercontent.com/41024075/63189365-0d3bfe00-c021-11e9-9f10-1ee1cfb3a91a.png)

**Comment by KatieWoe** [comment]
Above commits added to both branches.  @arouinfar if you need changes let me know.  Otherwise this can be closed.

**Comment by arouinfar** [comment]
Looks good to me. Thanks @KatieWoe!
