### ISSUE TITLE
Credits for 1.0

### ISSUE THREAD

**Issue by samreid** [phetsims/waves-intro#9]
We are about to create the first RC for Waves Intro and I'd like to make sure the QA credits are up-to-date (as much as possible) before creating the RC.  @KatieWoe can you please take a look and let me know if anything's missing or incorrect?

**Comment by samreid** [comment]
Also co-assigning @arouinfar and/or @ariel-phet to verify the rest of the credits are correct.  (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks)

**Comment by arouinfar** [comment]
@samreid the credits look good to me. Generally speaking, I think the Waves Intro credits should match Wave Interference, except for when it comes to sound design credits (which won't apply to 1.0).

**Comment by samreid** [comment]
We will need to incorporate changes from https://github.com/phetsims/wave-interference/issues/369 for wave-interference.  Self-assigning for that part.

**Comment by samreid** [comment]
I copied the credits.thanks from wave-interference.  All credits now match wave-interference.  Leaving assigned to @KatieWoe to check on the QA credits.

**Comment by samreid** [comment]
@KatieWoe are the credits for Waves Intro and Wave Interference correct in the latest RCs?

**Comment by KatieWoe** [comment]
Add Logan Bray please.

**Comment by samreid** [comment]
I added in both the branches and spot tested.

**Comment by samreid** [comment]
I deployed with the revised credits, closing.
